# ===============================
# Logging / Output
# ===============================
log_name: "exp/STT-Indomain"
use_wandb: true

# ===============================
# Training parameters
# ===============================
batch_size: 16
epochs: 1000
warmup_epochs: 1
multi_epochs_dataloader: true
find_unused_parameters: true

# ===============================
# Aligner Warmup
# ===============================
enable_projection_warmup: true
projection_warmup_epochs: 3
warmup_modalities: ["vision", "tactile"]

# ===============================
# Optimizer / LR parameters
# ===============================
weight_decay: 0.05
blr: 1e-5              # base lr (absolute lr = blr * total_batch / 256)

# ===============================
# Dataset parameters
# ===============================
datasets_dir: "/path/to/SeeingThroughTouch/datasets"
datasets: ["touch_and_go"]
active_modality_names: ["vision", "tactile"]
test_split_type: "no_inter"
dataset_rectangular_padding: false

# Touch Instance + MDP settings
TouchInstance_file: "/path/to/SeeingThroughTouch/datasets/touch_and_go/metadata/train_nointer_touch_instances.txt"
MDP_mode: "In-domain"  # Options: null, "In-domain", "Out-domain"

# ===============================
# Vision encoder parameters
# ===============================
vision_pretrained_weight: "dino"
vision_dino_version: "v3"
vision_dino_model: "dinov3_vits16"
vision_projection_type: "aligner"
vision_use_self_attention: false
vision_use_attention_pooling: false

# ===============================
# Tactile encoder parameters
# ===============================
tactile_pretrained_weight: "dino"
tactile_dino_version: "v3"
tactile_dino_model: "dinov3_vits16"
tactile_dino_finetuning_trainable_layers: [0,1,2,3,4,5,6,7,8,9,10,11]
tactile_projection_type: "aligner"
tactile_train_patch_embed: "full"
tactile_use_self_attention: false
tactile_use_attention_pooling: false

# ===============================
# Projection / Embedding
# ===============================
projection_lr_ratio: 1.0
target_embedding_dim: 384
forward_option: "average_pooling"
aggregation_pool: "max"
use_aggregation_loss: true

# ===============================
# Runtime / Misc
# ===============================
num_workers: 16
dinov3_repo_local: "/path/to/dinov3" # Update this path to your local DINOv3 repository
seed: 30